In [3]:
import numpy as np

In [5]:
M = np.array([[1, 1, 0, 0], 
             [1, 0, 1, 0],
             [0, 0, 0, 0], 
             [0, 1, 1, 1]])

In [6]:
n = len(M)

### Phản xạ

In [9]:
a = 1
for i in range(n):
    a = a and M[i, i] == 1
a

False

### Đối xứng

In [10]:
a = 1
for i in range(n):
    for j in range(n):
        a = a and M[i, j] == M[j, i]
a

False

In [13]:
M2 = M.dot(M)
M2.astype(bool).astype(int)
M2 - M

array([[ 1,  0,  1,  0],
       [ 0,  1, -1,  0],
       [ 0,  0,  0,  0],
       [ 1,  0,  1,  0]])

In [14]:
M2 <= M

array([[False,  True, False,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True],
       [False,  True, False,  True]])

In [16]:
# Check bắc cầu
M2 = M.dot(M)
M2.astype(bool).astype(int)
bool((M2 <= M).prod())

False

In [18]:
M.T == M

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True, False,  True, False],
       [ True, False, False,  True]])

In [19]:
a = 1
for i in range(n):
    for j in range(n):
        md = i == j or M[i, j] * M[j, 1] != 1
        a = a and md
a

False